### ISSUE TITLE
IMDB Command

### ISSUE THREAD

**Issue by KieranRobson** [KieranRobson/Clarence-Bot#57]
https://www.npmjs.com/package/imdb

/imdb <movie name>

See also: https://www.npmjs.com/package/name-to-imdb

**Comment by OndrejMarcncak** [comment]
Hi, i would like to know if it is possible to work on this issue.

**Comment by KieranRobson** [comment]
Go ahead @OndrejMarcncak

**Comment by OndrejMarcncak** [comment]
Thank you, could you give me more info about this task?

**Comment by OndrejMarcncak** [comment]
Hi @KieranRobson , 

I was not able to use module **imdb**, because it is **outdatedand** its not returning valid values. Another modue you have metioned does not have enought fields (in my oppinion), so i have used module **node-movie** (https://www.npmjs.com/package/node-movie), which is using imdb data too, and it has **MIT** licence.

The command has signature **/imdb**, with 1 required parameter **name** (name of the movie or Tv show). I am also attaching preview of the command.

<img width="302" alt="clerence_imdb" src="https://user-images.githubusercontent.com/114945038/200111987-51abf075-45fe-4e2e-acdc-072a2d617538.png">

**Comment by KieranRobson** [comment]
That's looks great! Thanks for taking the time to work on it @OndrejMarcncak!

**Comment by KieranRobson** [comment]
Implemented in #78
